### ISSUE TITLE
Multiple configuration files are not supported

### ISSUE THREAD

**Issue by marco-eckstein** [detekt/detekt-intellij-plugin#117]
detekt supports multiple configuration files, but the plugin only supports one. I have split my detekt configuration into multiple files: one shared across all projects and one project-specific. So, I cannot use the plugin.

**Comment by MarcusWolschon** [comment]
Yes, project specific Detekt config is a must.
Just like Lint and code style are project specific.

**Comment by arturbosch** [comment]
Multiple configuration files are supported by using a path separator char like

![Screenshot from 2022-06-27 18-31-44](https://user-images.githubusercontent.com/20924106/175990365-583e84e2-e63e-440a-9743-1eeb4dd7546d.png)

Unfortunately the file chooser for the config file does not support choosing multiple files (PRs welcome).

**Comment by stenzengel** [comment]
Since the file path separator is Windows/Linux specific (for Windows a semicolon and for Linux a colon must be used), this causes a problem, if we would like to commit the file `.idea/detekt.xml` in Git (even if the folder .idea is Git-ignored) to share the configuration of the Detekt plugin (in addition to the Detekt rules).

The cause seems to be `path.trim().split(File.pathSeparator)` in ProjectUtils.extractPaths. Could this be changed to a way which works for both operating systems? 

(Only the colon/semicolon difference causes problems, using slash on Windows systems is not a problem.)
