### ISSUE TITLE
Support ordered configuration files to be able to override rules deterministically

### ISSUE THREAD

**Issue by stenzengel** [detekt/detekt-intellij-plugin#385]
It seems to me that a deterministic ordering of configuration files is not supported anymore, after the implementation of #240. In our case the ordering is important, because a project specific configuration file (in my case `detektrules.yml`) should override the configuration of a generic configuration `.detekt/detektrules.yml` (i.e. with the same name but different folder). 

It seems that the ordering is not considered by `detekt-intellij-plugin` anymore, because 

1. rules the are enabled in `.detekt/detektrules.yml`, but disabled in `detektrules.yml` are still executed (at least sometimes, but not sure if always)
2. there are no Up/Down buttons in the configuration dialog
3. the XML element `<set>` is used inside `<option name="configurationFilePaths">` which implies a non-ordering

Can you confirm my presumption? 
Would it be possible to implement a deterministic ordering?

.idea/detekt.xml (with old and new configuration):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project version="4">
  <component name="DetektPluginSettings">
    <option name="configurationFilePaths">
      <set>
        <option value="$PROJECT_DIR$/.detekt/detektrules.yml" />
        <option value="$PROJECT_DIR$/detektrules.yml" />
      </set>
    </option>
  </component>
  <component name="DetektProjectConfiguration">
    <enableDetekt>true</enableDetekt>
    <configPaths>.detekt/detektrules.yml;detektrules.yml</configPaths>
  </component>
</project>
```

**Comment by stenzengel** [comment]
@rock3r Can you confirm the problem? Do you know about a work-around? (Friendly ping, because the issue tracker is flooded with exception message issues.)

**Comment by rock3r** [comment]
I'm sorry, I have been incredibly busy recently and haven't kept an eye on this (nor was I tagged before, so no pings got to me). A fix would be replacing the files set in the implementation with a list and adding up/down actions on the table that you set config files into. I may get around to it but most likely not before early next year, since I don't have much capacity during the holidays.

IIRC the whole reason why it was a files set and not a list was because that was a built in facility that IJ provides. I also had no idea order matters, as I have never used more than one config file outside of basic smoke testing of the plugin code. Sorry about that.
