### ISSUE TITLE
Warning ranges not consistent with editor content

### ISSUE THREAD

**Issue by karollewandowski** [detekt/detekt-intellij-plugin#57]
Please see recording: https://i.imgur.com/dcc9gDf.mp4.

Maybe there is some  inconsistency in computing indentations?

It was recorded in IntelliJ IDEA Ultimate 2019.3.

EDIT:
After a few more tests it looks like analysis is run with delay (what is reasonable) and if we insert some new text before annotated text, then it breaks positions. Sometimes it's fixed after a moment and sometimes stays broken until I type anything what is pretty annoying and distracting.

**Comment by ahampe** [comment]
The annotator in this plugin receives `PsiFile`s which are updated as you edit, but, interestingly, the `VirtualFile`s associated with them aren't updated, at least from my debugging. Perhaps some kind of caching issue? I would think the fix would be making it so that the core detekt library can analyze `PsiFile`s directly so that the highlights can be applied accurately, or somehow triggering an update of the virtual file and waiting for it to reflect the changes in the `PsiFile`. I don't know how to implement either of these, just wanted to note.

**Comment by karollewandowski** [comment]
Hi, when can we expect 1.0.0-RC1 available in plugins repo? I can see that both tasks from this milestone are finished.
