### ISSUE TITLE
Suggestion - add Dependabot and branch 'dev', for faster bump of detekt-core version

### ISSUE THREAD

**Issue by pinkasey** [detekt/detekt-intellij-plugin#89]
You're probably familiar with Dependabot:
https://seankilleen.com/2019/07/automagically-update-your-package-dependencies-with-dependabot-for-free/

The motivation -
[detekt](https://github.com/detekt/detekt) changes more frequently than [detekt-intellij-plugin](https://github.com/detekt/detekt-intellij-plugin),
And IMO - changes in **detekt** have higher impact on me as a user of this IntelliJ plugin, than changes to the plugin itself.
I would like changes from **detekt** to reach my IntelliJ faster,
independently of features of this plugin.

Maybe a good way to do this is adding a `dev` branch, to work on new-features,
so that `master` can be easily updated to latest detekt-version and released.

WDYT?
(BTW - is that the right place to write this?)

**Comment by arturbosch** [comment]
Thanks for the suggestion.
Unfortunately Dependabot does not support the Gradle Kotlin DSL yet.

Feel free to push PRs with detekt updates if you have the resources left. I will gladly merge them into the master branch. No need for a dev branch for now as we do not have enough resources to push more features for this plugin.

Generally I wait some time between releasing a new Intellij/Sonar plugin version because it has more releasing overhead to include any bugfix releases for detekt if needed.

**Comment by pinkasey** [comment]
Thanks
I'll try to make time to contribute
(Not familiar with Gradle and IntelliJ plugin development, so there's a learning curve there)

**Comment by arturbosch** [comment]
Version 1.2.0 was published, available at bintray and github now and in intellij marketplace in a few days :partying_face:

**Comment by pinkasey** [comment]
Hurray!
🥳
